# Generated by Django 3.2 on 2023-03-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_notes',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='todo_notes',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
