# Generated by Django 3.2 on 2023-04-01 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TODO', '0003_auto_20230313_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user_set',
        ),
        migrations.AddField(
            model_name='project',
            name='user_set',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
